name: 'Tmp Artifact'
description: 'Upload to temporary artifact server'
inputs:
  file:  # id of input
    description: 'File'
    required: true
  url:  # id of input
    description: 'Server url'
    required: true
outputs:
  uuid:
    description: 'Uuid for getting data'
runs:
  using: 'docker'
  image: 'docker://nuimk/tmp-artifact-action:dev'
  args:
    - action
    - upload
    - --server=${{ inputs.server }}
    - ${{ inputs.file }}
